apiVersion: v1
kind: Service
metadata:
    name: server-srv
spec:
    type: LoadBalancer
    selector:
        app: server
    ports:
        - protocol: TCP
          port: 80
          targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: server-depl
    labels:
        app: server
spec:
    replicas: 1
    selector:
        matchLabels:
            app: server
    template:
        metadata:
            labels:
                app: server
        spec:
            containers:
                - name: server
                  image: unsivilaudio/first-app
                  ports:
                      - containerPort: 3000
