apiVersion: v1
kind: Service
metadata:
    name: auth-srv
spec:
    type: ClusterIP
    selector:
        app: auth
    ports:
        - name: auth-web
          protocol: TCP
          port: 80
          targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: auth
    template:
        metadata:
            labels:
                app: auth
        spec:
            containers:
                - name: auth
                  image: unsivilaudio/kub-auth:latest
                  resources:
                      limits:
                          cpu: '1'
                          memory: '128M'
