apiVersion: v1
kind: Service
metadata:
    name: frontend-srv
spec:
    type: LoadBalancer
    selector:
        app: frontend
    ports:
        - name: frontend-web
          protocol: TCP
          port: 80
          targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: frontend
    template:
        metadata:
            labels:
                app: frontend
        spec:
            containers:
                - name: frontend
                  image: unsivilaudio/kub-web:latest
