apiVersion: v1
kind: Service
metadata:
    name: tasks-srv
spec:
    type: LoadBalancer
    selector:
        app: tasks
    ports:
        - name: tasks-web
          protocol: TCP
          port: 8000
          targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: tasks-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: tasks
    template:
        metadata:
            labels:
                app: tasks
        spec:
            containers:
                - name: tasks
                  image: unsivilaudio/kub-tasks:latest
                  env:
                      - name: AUTH_ADDRESS
                        value: 'auth-srv.default'
                      - name: TASKS_FOLDER
                        value: 'tasks'
                  resources:
                      limits:
                          cpu: '1'
                          memory: '128M'
