apiVersion: v1
kind: Service
metadata:
    name: story-srv
spec:
    type: LoadBalancer
    selector:
        app: story
    ports:
        - protocol: TCP
          port: 80
          targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: story-depl
    labels:
        app: story
spec:
    replicas: 1
    selector:
        matchLabels:
            app: story
    template:
        metadata:
            labels:
                app: story
        spec:
            containers:
                - name: story
                  image: unsivilaudio/kub-story
                  imagePullPolicy: Always
                  env:
                      - name: STORY_FOLDER
                        valueFrom:
                            configMapKeyRef:
                                name: data-store-env
                                key: folder
                  volumeMounts:
                      - mountPath: /app/story
                        name: story-volume
                  resources:
                      limits:
                          cpu: '1'
                          memory: '128M'
            volumes:
                - name: story-volume
                  persistentVolumeClaim:
                      claimName: host-pvc
