apiVersion: v1
kind: PersistentVolume
metadata:
    name: host-pv
spec:
    capacity:
        storage: 256M
    volumeMode: Filesystem
    storageClassName: standard
    accessModes:
        - ReadWriteMany
        - ReadWriteOnce
        - ReadOnlyMany
    hostPath:
        path: /data
        type: DirectoryOrCreate
